# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/helmholtz-juniors/"

[social.params]
icon = "brand-github"


[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/helmholtz.juniors"

[social.params]
icon = "brand-facebook"


[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/HelmholtzJrs"

[social.params]
icon = "brand-twitter"


[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/helmholtz.juniors/"

[social.params]
icon = "brand-instagram"


[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://de.linkedin.com/company/helmholtz-juniors"

[social.params]
icon = "brand-linkedin"
